### ISSUE TITLE
Error Loading osascript

### ISSUE THREAD

**Issue by kartharer** [randomknowledge/Cactus_Refactored#3]
There is an error loading the Adobe Unit Types osascript under OSX 1.6.6+. It is used to refresh a page in the browser. 

Solution: Install the update from Adobe under /Library/ScriptingAdditions available here: http://helpx.adobe.com/photoshop/kb/unit-type-conversion-error-applescript.html 

(This is not an error of Cactus but should be available in the documentation.)

**Comment by randomknowledge** [comment]
Thanks for the info, I'll add that to the Readme
